### ISSUE TITLE
no e2e tests for email-tagsinput

### ISSUE THREAD

**Issue by individual-it** [avocode/avocode-email-tagsinput#19]
I cannot find any e2e tests that check the `email-tagsinput` package.

@comatory if you want to have specific e2e tests for that package assign @Talank  to this issue and he can take care of it

**Comment by comatory** [comment]
I don't think this approach is necessary. This is public project and everyone is free to open issue and submit PR.

This project is maintained under Avocode company so I can only assign people to issues within it. @Talank is free to open PR and link it here if he wishes to do so.

**Comment by comatory** [comment]
Thanks @Talank for adding basic E2E tests, they should serve as a good starting point for further development.
